services:
  - type: web
    name: cobranca-pro-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_VERSION
        value: "20.11.1"
      - key: MONGODB_URI
        sync: false
      - key: ZAPI_INSTANCE_ID
        sync: false
      - key: ZAPI_TOKEN
        sync: false
      - key: ZAPI_CLIENT_TOKEN
        sync: false
      - key: NEXTAUTH_URL
        sync: false
