services:
  - type: web
    name: cobranca-pro-backend
    env: node
    nodeVersion: "20.11.1"
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "20.11.1"
